### ISSUE TITLE
Complete EJ2 Extensions

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/Wisej-Ext-Syncfusion2#1]
**Mark control complete when:**
1. Sample control works (visually correct).
2. Added several different property toggles and verify they work
3. Ensure the style and sizing of these properties follow a pattern (i.e. textboxes then buttons, same dimensions)
3. Documentation links filled out
4. Committed changes

**Controls:**
- [x] AccumulationChart
- [x] BulletChart
- [x] Calendar
- [x] Chart
- [x] ChipList
- [x] CircularGauge
- [x] ColorPicker
- [x] DatePicker
- [x] DateRangePicker
- [x] DateTimePicker
- [x] Diagram (Complex test can we have schedule a test case ?)
- [x] DocumentEditor (Already have test)
- [x] DropDownList
- [x] DropDownTree
- [x] FileManager
- [x] Gantt
- [x] Grid
- [x] HeatMap
- [x] Kanban
- [x] LinearGauge
- [x] ListBox
- [x] ListView
- [x] Maps (Already have a test)
- [x] Menu (Docking problems)
- [x] MultiSelect
- [x] PDFViewer (Already have a test)
- [x] PivotView
- [x] ProgressBar
- [x] ProgressButton
- [x] QueryBuilder (Already have small test)
- [x] RangeNavigator
- [x] RichTextEditor (Already have a test)
- [x] Schedule
- [x] Slider
- [x] SmithChart
- [x] Sparkline
- [x] SplitButton
- [x] Spreadsheet (Already have atest)
- [x] StockChart
- [x] TimePicker
- [x] Toolbar
- [x] TreeGrid
- [x] TreeMap
- [x] TreeView
- [x] Uploader

**Comment by keevBush** [comment]
@LRufenacht Menu (with dock or not) have some problem with orientation option property

**Comment by keevBush** [comment]
@LRufenacht Schedule create infinte loading after change properties

**Comment by LRufenacht** [comment]
Thanks @keevBush, fixed and checked into SVN. please verify the fix.
